### PR TITLE
[Sonic Origins] Legacy global functions & GameStartup library

### PR DESCRIPTION
**Pull request by MegAmi24**
This PR removes the structs for legacy game global variables and replaces them with `GetLegacyGlobalID`, `GetLegacyGlobalByName`, and `SetLegacyGlobalByName` functions, similar to what's found inside RSDK itself. `GetLegacyGlobalID` looks up the numerical ID of a global variable based off of its name, and the other two functions use that to get or set the value of the variable. The benefits to these functions are:
- No need for storing large structs for in the RSDK library.
- The global variable doesn't have to be a specific ID for these functions to work, allowing the same function call in a code to get or set that variable in multiple games (see the Enable Lives codes as an example).
- Mods can add custom global variables in a game's GameConfig.bin file and then easily set that variable through an HMM code to act as a config option. This technique would be more powerful if paired with a hypothetical mod that adds the Game.xml functionality from the RSDK Decompilations.

The `Bridge.SetGlobalVariables` library is also updated and renamed to `GameStartup`. The updated library allows codes to add their own global variables to a list that the library then uses to set those variables in-game.

This PR also marks the `Enable 7th Chaos Emerald` code as experimental and adds the `Enable Original Camera Tracking` code.

### CODE REVIEW

**Comment by thesupersonic16** [comment]
Sorry for the late reply, do we really need to keep `Bridge.SetGlobalVariables` when `RSDK.SetLegacyGlobalByName` exists?

**Comment by MegAmi24** [comment]
> Sorry for the late reply, do we really need to keep `Bridge.SetGlobalVariables` when `RSDK.SetLegacyGlobalByName` exists?

Simply setting the variables every frame causes issues with the shield/item related codes, as since HMM only runs its code at the end of each frame, and loading the game loads both the GameConfig and the starting scene on the same frame (there is relevant shield and monitor code that runs in ObjectStartup), the codes will not properly apply when initially loading the game from a save file or My Data.

The unmanaged function within the Bridge is ran when HE2 is setting Origins specific variables (e.g. playMode and coinMode), which fixes this issue. Since there are six codes for setting variables like this, I use a Bridge to keep things clean. Also, if it's possible, I'd eventually like to make it so codes can specify their own variables to set other than the ones currently supported in the Bridge.

**Review by thesupersonic16 — APPROVED** [review]
LGTM

**Review by thesupersonic16 — APPROVED** [review]
LGTM

**Comment by MegAmi24** [comment]
Apologies if I sound impatient, but is there a reason this two month old PR hasn't been merged yet despite the changes being approved twice now? Is someone else other than SS16 supposed to approve the changes as well?

**Comment by thesupersonic16** [comment]
I was expecting someone else to merge it, but I can do it.

**Pull request merged**
