### PR TITLE
[Sonic Origins] Various Additions and Fixes

### PR DESCRIPTION
**Pull request by MegAmi24**
- Added structs for global variables for Sonic 1, Sonic 2, and Sonic CD, along with `Get[Game]Globals()` functions to return them (and updated existing codes to use them where appropriate)
- Added `GetEngineVersion()`, `GetCurrentGame()`, and `GetPlayMode()` functions to the RSDK library (and updated existing codes to use them where appropriate)
- Fixed `GetRSDKGlobalsPtr()` returning a pointer to a globals pointer instead of the globals pointer itself
- Removed `GetRSDKGlobalsOffset()` and `GetRSDKGlobalsAbsPtr()` as their existence was questionable and have no purpose now that `GetRSDKGlobalsPtr()` is fixed
  - Some mods will break and will have to be updated due to this change. If this is an issue, I can add them back.
- The `Init()` function in the RSDK library now has the `LibraryInitializer` attribute
- The `Helpers` and `StringMapOperation` libraries are now Global libraries
- Reworked the Sonic 1/2 global variable codes; instead of constantly setting the global variables through separate codes, the new `SetGlobalVariables` bridge library is now used to handle which variables are set in an unmanaged function called when the games load. This fixes the initial stage load issue with the shield/item codes.
- The super music variable is now set normally instead of using `WriteProtected` in `Disable Super Music`
- Added `Enable Blue Spheres Options in Title Screen` and various medal mod/secret codes for Sonic 3 & Knuckles

### CODE REVIEW

**Comment by hyperbx** [comment]
It would be worth making a function in the RSDK library instead to detect which game is currently running, rather than working it out on a per-code basis.

For example;
```cs
public EGame GetCurrentGame()
{
    // ...
    return EGame .Unknown;
}

enum EGame
{
    Unknown = -1,
    Sonic1,
    SonicCD,
    Sonic2,
    Sonic3K
}
```

**Comment by MegAmi24** [comment]
That'd be great, however my current implementation of the game check can only distinguish between Sonic 1 and 2; it doesn't work for CD or S3&K. I'm not sure how Origins properly stores which game you're currently playing, and even if I did, writing SigScans for RAM memory sounds like a nightmare to me at the moment.

**Comment by MegAmi24** [comment]
Alright, I've added about all I wanted to.

**Review by hyperbx — APPROVED** [review]
LGTM, will wait on @thesupersonic16's opinion as he'd be better suited to approve RSDK stuff.

**Comment by thesupersonic16** [comment]
All codes for S3K appear to be working as expected.

**Review by thesupersonic16 — APPROVED** [review]
LGTM

**Pull request merged**
