### PR TITLE
[Sonic Origins] Sonic 1 & 2 game option codes

### PR DESCRIPTION
**Pull request by MegAmi24**

### CODE REVIEW

**Comment by thesupersonic16** [comment]
Can you explain how to test some of these codes? Also globals are writable memory, meaning WriteProtected shouldn't be needed.

**Comment by MegAmi24** [comment]
> Can you explain how to test some of these codes like "Enable 7th Chaos Emerald"? Also globals are writable memory, meaning WriteProtected shouldn't be needed.

The quickest way to test these would be to go into the Level Select for the games and observe the default game options (in Sonic 2, you can access these by playing sound test number 00 three times). Super Tails isn't togglable via the Level Select in Sonic 2, however, so you'll have to input the All Emeralds sound test code (04, 01, 02, 06), then go into a stage and try transforming.

**Comment by thesupersonic16** [comment]
Codes appear to be working except for Enable Super Tails, is there something I need to do perform the transformation? and does it conflict with debug mode?

**Comment by MegAmi24** [comment]
> Codes appear to be working except for Enable Super Tails, is there something I need to do perform the transformation? and does it conflict with debug mode?

Odd, it worked when I tested it. It should work the same way as the other characters (make sure you're pressing Y to transform and not one of the jump buttons), and I tested these codes with Debug Mode enabled, so it shouldn't conflict.

**Comment by MegAmi24** [comment]
Just tested the code again, and yep, it works for me. Not sure what's happening on your end, unless you're just not doing it correctly. I should note this was tested without any script mods or mods that affect the Data assets (only have Blur Fix, OriginsDevMode, and a few audio mods on).

https://github.com/hedge-dev/HMMCodes/assets/7158344/dca86e89-a946-4a6f-9aa9-a5a414c31f3c

**Comment by thesupersonic16** [comment]
Just tried it again while making sure I am pressing the right button and it does work, I likely pressed the wrong buttons like I always do in this game.

**Review by thesupersonic16 — APPROVED** [review]

**Pull request merged**
