### PR TITLE
[Sonic Frontiers] Added code "Enable Dynamic Resolution"

### PR DESCRIPTION
**Pull request by angryzor**
Added a code that re-enables the built-in dynamic resolution system.

### CODE REVIEW

**Review by ActualMandM — CHANGES_REQUESTED** [review]
Put the game version in the code title since this is using addresses instead of signature scans. Look at Smooth Camera and Fix RenderDoc Captures for reference.

**Comment by angryzor** [comment]
Hmm, I'll just do the scans instead.

**Comment by hyperbx** [comment]
This should be under the Graphics/Display category imo

**Comment by angryzor** [comment]
Handled review comments, added comments in the code and fixed an oversight I didn't notice while debugging (that the graphics options extension of FxParamManager turns the dynamic resolution feature off if you're not overriding it).

**Review by ActualMandM — APPROVED** [review]
LGTM

**Review by hyperbx — APPROVED** [review]
LGTM

**Pull request merged**
